sudo: true
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo
script: hugo --baseUrl="https://baraka-sdw.github.io/"
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: baraka-sdw/baraka-sdw.github.io
    fqdn: www.baraka.ink
    target_branch: master
    email: guiguzisong@gmail.com
    name: baraka-sdw