theme="LeaveIt"
baseURL = "http://guiguzi21.github.io/"
languageCode = "zh-cn'"
title = "Baraka的博客"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

[params]
  author = "Baraka"
  avatar = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/octocat.png" # optional
  #profile = "/img/octocat.png" # optional
  cover = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/octocat.png" # optional
  github = "guiguzi21" # optional
  linkedin = "宋德伟" # optional
  favicon = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/favicon.ico"
  siteStartYear = 2018
  motto = "知足常乐 风清月明"
  cdn_url = ""           # Base CDN URL
  home_mode = "" # post or other
  google_verification = ""
  description = "" # site description
  keywords = "" # site keywords
  beian = ""
  baiduAnalytics = ""
  license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
  since = 2017
[permalinks]
  post = "/:year/:month/:day/:filename/" # optional

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
 [params.social]
      GitHub = "guiguzi21"
      Email   = "guiguzisong@gmail.com"
      Wechat = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/WechatIMG2.jpeg"  # Wechat QRcode image
      Telegram = "SongDeWei"
