theme="LeaveIt"
baseurl = "http://guiguzi21.github.io/"
languageCode = "zh-cn'"
title = "Baraka的博客"
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

[params]
  author = "Baraka"
  avatar = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/octocat.png" # optional
  #profile = "/img/octocat.png" # optional
  cover = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/octocat.png" # optional
  github = "guiguzi21" # optional
  linkedin = "宋德伟" # optional
  favicon = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/favicon.ico"
"
  siteStartYear = 2018
  motto = "知足常乐 风清月明"

[permalinks]
  post = "/:year/:month/:day/:filename/" # optional
