theme="LeaveIt"
baseURL = "http://baraka-sdw.github.io/"
languageCode = "zh-cn'"
title = "Baraka的博客"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
comment = true            # 是否开启评论
toc = true                # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc

[params]
  author = "Baraka"
  avatar = "//sdw-1254060699.file.myqcloud.com/blog_img/octocat.png" # optional
  #profile = "/img/octocat.png" # optional
  cover = "//sdw-1254060699.file.myqcloud.com/blog_img/octocat.png" # optional
  github = "baraka-sdw" # optional
  linkedin = "宋德伟" # optional
  favicon = "//sdw-1254060699.file.myqcloud.com/blog_img/cat.ico"
  siteStartYear = 2018
  motto = "知足常乐 风清月明"
  cdn_url = ""           # Base CDN URL
  home_mode = "" # post or other
  google_verification = ""
  description = "" # site description
  keywords = "" # site keywords
  beian = ""
  baiduAnalytics = ""
  license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
  since = 2017
[permalinks]
  post = "/:year/:month/:day/:filename/" # optional

[blackfriday]
    hrefTargetBlank = true
    nofollowLinks = true
    noreferrerLinks = true
[menu]
  [[menu.main]]
    name = "归档"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "观影"
    url = "/movie/"
    weight = 5

  [[menu.main]]
    name = "阅读"
    url = "/book/"
    weight = 6

 [params.social]
      GitHub = "baraka-sdw"
      Email   = "guiguzisong@gmail.com"
      Wechat = "//sdw-1254060699.cos.ap-chengdu.myqcloud.com/blog/WechatIMG2.jpeg"  # Wechat QRcode image
      Telegram = "SongDeWei"

  # Gitalk 评论配置（gitalk 请参考：https://github.com/gitalk/gitalk）
  [params.gitalk]
      owner = "baraka-sdw"   # Your GitHub ID
      admin = "baraka-sdw"      # GitHub repository owner and collaborators
      repo = "baraka-sdw.github.io"               # The repo to store comments
      clientId = "aca3cfd7362cc2a1edbf"           # Your client ID
      clientSecret = "157a41360e221c0e42aa7ac3ddc9b8c2322924d3"       # Your client secret
      countSign = "条评论"
